SHELL_KEYWORDS = ["build", "install", "prep", "check", "clean", "pre", "preun", "pretrans", "post", "postun",
                  "posttrans", "configure", "transfiletriggerin", "transfiletriggerpostun", "triggerun"]
OBS_LINES_KEYWORDS = ["description", "files"]
RARE_KEYWORDS = ["triggerun", "transfiletriggerin", "transfiletriggerpostun"]
MAIN_SHELL_KEYWORDS = ["build", "install", "prep", "check", "clean"]
MACROS_KEYWORDS = ["%package_help"]

HEADERS = ('package',
           'description',
           'prep',
           'build',
           'install',
           'clean',
           'check',
           'preun',
           'pretrans',
           'pre',
           'postun',
           'posttrans',
           'post',
           'files',
           'changelog',
           'triggerun',
           'transfiletriggerin',
           'transfiletriggerpostun',
           'include')
SINGLES = ('Summary',
           'Name',
           'Version',
           'Epoch',
           'URL',
           'Group',
           'BuildArch',
           'Source',
           'Patch',
           'Prefix',
           'License',
           "Release",
           "Recommends",
           "ExclusiveArch")
REQUIRES = ('BuildRequires',
            'Requires',
            'Requires(post)',
            'Requires(postun)',
            'Requires(posttrans)',
            'Requires(pre)',
            'PreRequires', 'PreReq', 'Prereq',  # alias in old spec
            'Requires(preun)',
            'Requires(pretrans)',
            'Provides',
            'Obsoletes',
            'Conflicts',
            'BuildConflicts',
            'FilesJudgement',
            )
SKIPS = ('BuildRoot',)

ORDER_ENTRIES = ['Macros',
                 'Name',
                 'Summary',
                 'Version',
                 'Release',
                 'Epoch',
                 'Group',
                 'License',
                 'URL',
                 'SCM',
                 'Sources',
                 'ExtraSources',
                 'Patches',
                 'Description',
                 'Requires',
                 'RequiresPre',
                 'RequiresPreUn',
                 'RequiresPreTrans',
                 'RequiresPost',
                 'RequiresPostUn',
                 'RequiresPostTrans',
                 'BuildRequires',
                 'Provides',
                 'Obsoletes',
                 'Conflicts',
                 'ConfigOptions',
                 'BuildArch',
                 'ExclusiveArch',
                 'LocaleName',
                 'LocaleOptions',
                 'Files',
                 'FilesInput',
                 'SupportOtherDistros',
                 'ExcludeArch',
                 'Recommends',
                 'Supplements',
                 'Prefix',
                 'OrderWithRequires',
                 'Suggests',
                 'IncludeSource',
                 'FilesJudgement',
                 'rpmMacros',
                 'rpmGlobal',
                 'useFlag'
                 ]

SPEC_EXTRA_KEYS = {
        # key -> ( nkey, nsubkey)
        #                ^^ None means to use <pkg_name>
        'Files': ('files', None),
        'macros': ('macros', None),
        'setup': ('setup', None),
        'define': ('define', None),
        'undefine': ('undefine', None),
        'global': ('global', None),
        'PostMakeInstallExtras': ('install', 'post'),
        'PreMakeInstallExtras': ('install', 'pre'),
        'PostMakeExtras': ('build', 'post'),
        'PreMakeExtras': ('build', 'pre'),
    }

RPM_GLOBAL_MACROS = {
    "GNAT_arches": "%{GPRbuild_arches} %{generic_arches}",
    "GPRbuild_arches": "%{generic_arches}",
    "-20:": "warn\t<builtin>",
    "__7zip": "/usr/bin/7za",
    "___build_args": "-e",
    "___build_cmd": "%{?_sudo:%{_sudo} }%{?_remsh:%{_remsh} %{_remhost} }%{?_remsudo:%{_remsudo} }%{?_remchroot:%{_remchroot} %{_remroot} }%{___build_shell} %{___build_args}",
    "___build_post": "RPM_EC=$?\n  for pid in $(jobs -p); do kill -9 ${pid} || continue; done\n  exit ${RPM_EC}\n%{nil}",
    "___build_pre": "RPM_SOURCE_DIR=\"%{u2p:%{_sourcedir}}\"\n  RPM_BUILD_DIR=\"%{u2p:%{_builddir}}\"\n  RPM_OPT_FLAGS=\"%{optflags}\"\n  RPM_LD_FLAGS=\"%{?build_ldflags}\"\n  RPM_ARCH=\"%{_arch}\"\n  RPM_OS=\"%{_os}\"\n  RPM_BUILD_NCPUS=\"%{_smp_build_ncpus}\"\n  export RPM_SOURCE_DIR RPM_BUILD_DIR RPM_OPT_FLAGS RPM_ARCH RPM_OS RPM_BUILD_NCPUS RPM_OPT_FLAGS\n  RPM_DOC_DIR=\"%{_docdir}\"\n  export RPM_DOC_DIR\n  RPM_PACKAGE_NAME=\"%{NAME}\"\n  RPM_PACKAGE_VERSION=\"%{VERSION}\"\n  RPM_PACKAGE_RELEASE=\"%{RELEASE}\"\n  export RPM_PACKAGE_NAME RPM_PACKAGE_VERSION RPM_PACKAGE_RELEASE\n  LANG=C\n  export LANG\n  unset CDPATH DISPLAY ||:\n  %{?buildroot:RPM_BUILD_ROOT=\"%{u2p:%{buildroot}}\"\n  export RPM_BUILD_ROOT}\n  %{?_javaclasspath:CLASSPATH=\"%{_javaclasspath}\"\n  export CLASSPATH}\n  PKG_CONFIG_PATH=\"${PKG_CONFIG_PATH}:%{_libdir}/pkgconfig:%{_datadir}/pkgconfig\"\n  export PKG_CONFIG_PATH\n  CONFIG_SITE=${CONFIG_SITE:-NONE}\n  export CONFIG_SITE\n  \n  %[%{verbose}?\"set -x\":\"\"]\n  umask 022\n  cd \"%{u2p:%{_builddir}}\"",
    "___build_shell": "%{?_buildshell:%{_buildshell}}%{!?_buildshell:/bin/sh}",
    "___build_template": "#!%{___build_shell}\n%{___build_pre}\n%{nil}",
    "__apply_patch(qp:m:)": "%{lua:\nlocal file = rpm.expand(\"%{1}\")\nlocal num = rpm.expand(\"%{2}\")\nif posix.access(file, \"r\") then\n    local options = rpm.expand(\"%{-q} %{-p:-p%{-p*}} %{-m:-m%{-m*}}\")\n    local scm_apply = rpm.expand(\"%__scm_apply_%{__scm}\")\n    print(rpm.expand(\"%{uncompress:\"..file..\"} | \"..scm_apply..\" \"..options..\"  \"..file..\" \"..num..\"\\n\"))\nelse\n    print(\"echo 'Cannot read \"..file..\"'; exit 1;\"..\"\\n\")\nend}",
    "__ar": "ar",
    "__arch_install_post": "/usr/lib/rpm/check-buildroot",
    "__as": "as",
    "__awk": "gawk",
    "__brp_boot_efi_times": "/usr/lib/rpm/brp-boot-efi-times",
    "__brp_chrpath": "/usr/lib/rpm/brp-chrpath %{buildroot}",
    "__brp_compress": "/usr/lib/rpm/brp-compress",
    "__brp_elfperms": "%{_rpmconfigdir}/brp-elfperms",
    "__brp_ldconfig": "/usr/lib/rpm/brp-ldconfig",
    "__brp_python_bytecompile": "/usr/lib/rpm/brp-python-bytecompile \"%{__python}\" \"%{?_python_bytecompile_errors_terminate_build}\" \"%{?_python_bytecompile_extra}\"",
    "__brp_python_hardlink": "/usr/lib/rpm/brp-python-hardlink",
    "__brp_remove_la_files": "%{_rpmconfigdir}/brp-remove-la-files",
    "__brp_strip": "/usr/lib/rpm/brp-strip %{__strip}",
    "__brp_strip_comment_note": "/usr/lib/rpm/brp-strip-comment-note %{__strip} %{__objdump}",
    "__brp_strip_static_archive": "/usr/lib/rpm/brp-strip-static-archive %{__strip}",
    "__bzip2": "/usr/bin/bzip2",
    "__bzr": "/usr/bin/bzr",
    "__cat": "/usr/bin/cat",
    "__cc": "gcc",
    "__check_files": "%{_rpmconfigdir}/check-files %{buildroot}",
    "__chmod": "/usr/bin/chmod",
    "__chown": "/usr/bin/chown",
    "__cp": "/usr/bin/cp",
    "__cpp": "gcc -E",
    "__cxx": "g++",
    "__debug_install_post": "%{__find_debuginfo} \\\n    %{?_smp_build_ncpus:-j%{_smp_build_ncpus}} \\\n    %{?_missing_build_ids_terminate_build:--strict-build-id} \\\n    %{?_no_recompute_build_ids:-n} \\\n    %{?_include_minidebuginfo:-m} \\\n    %{?_include_gdb_index:-i} \\\n    %{?_unique_build_ids:--build-id-seed \"%{VERSION}-%{RELEASE}\"} \\\n    %{?_unique_debug_names:--unique-debug-suffix \"-%{VERSION}-%{RELEASE}.%{_arch}\"} \\\n    %{?_unique_debug_srcs:--unique-debug-src-base \"%{name}-%{VERSION}-%{RELEASE}.%{_arch}\"} \\\n    %{?_find_debuginfo_dwz_opts} \\\n    %{?_find_debuginfo_opts} \\\n    %{?_debugsource_packages:-S debugsourcefiles.list} \\\n    \"%{_builddir}/%{?buildsubdir}\"\n%{nil}",
    "__docdir_path": "%{_datadir}/doc:%{_datadir}/man:%{_datadir}/info:%{_datadir}/gtk-doc/html:%{_datadir}/gnome/help:%{?_docdir}:%{?_mandir}:%{?_infodir}:%{?_javadocdir}:/usr/doc:/usr/man:/usr/info:/usr/X11R6/man",
    "__file": "/usr/bin/file",
    "__find_debuginfo": "/usr/bin/find-debuginfo",
    "__find_provides": "%{_rpmconfigdir}/find-provides",
    "__find_requires": "%{_rpmconfigdir}/find-requires",
    "__gem": "/usr/bin/gem",
    "__git": "/usr/bin/git",
    "__global_cflags": "%{build_cflags}",
    "__global_compiler_flags": "-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches %{_hardened_cflags}",
    "__global_cxxflags": "%{build_cxxflags}",
    "__global_fcflags": "%{build_fflags}",
    "__global_fflags": "%{build_fflags}",
    "__global_ldflags": "%{build_ldflags}",
    "__global_provides_exclude_from": "%{?_docdir:%{_docdir}}",
    "__global_requires_exclude_from": "%{?_docdir:%{_docdir}}",
    "__gpg": "/usr/bin/gpg2",
    "__gpg_reserved_space": "4096",
    "__gpg_sign_cmd": "%{__gpg}\n\tgpg --no-verbose --no-armor \n\t%{?_gpg_digest_algo:--digest-algo %{_gpg_digest_algo}} \n\t--no-secmem-warning \n\t%{?_gpg_sign_cmd_extra_args:%{_gpg_sign_cmd_extra_args}} \n\t-u \"%{_gpg_name}\" -sbo %{__signature_filename} %{__plaintext_filename}",
    "__grep": "/usr/bin/grep",
    "__gzip": "/usr/bin/gzip",
    "__hg": "/usr/bin/hg",
    "__id": "/usr/bin/id",
    "__id_u": "%{__id} -u",
    "__install": "/usr/bin/install",
    "__isa": "%{__isa_name}-%{__isa_bits}",
    "__isa_bits": "64",
    "__isa_name": "x86",
    "__ld": "/usr/bin/ld",
    "__ln_s": "ln -s",
    "__lrzip": "/usr/bin/lrzip",
    "__lzip": "/usr/bin/lzip",
    "__make": "/usr/bin/make",
    "__mkdir": "/usr/bin/mkdir",
    "__mkdir_p": "/usr/bin/mkdir -p",
    "__mv": "/usr/bin/mv",
    "__objdump": "/usr/bin/objdump",
    "__os_install_post": "%{?__brp_ldconfig} \n    %{?__brp_compress} \n    %{!?__debug_package:\n    %{?__brp_strip} \n    %{?__brp_strip_comment_note} \n    } \n    %{?__brp_strip_static_archive} \n    %{?py_auto_byte_compile:%{?__brp_python_bytecompile}} \n    %{?__brp_python_hardlink} \n    %{?openEuler_delete_rpath:%{?__brp_chrpath}} \n%{nil}",
    "__patch": "/usr/bin/patch",
    "__perl": "/usr/bin/perl",
    "__perl_check_pre": "%{expand:\n%{?__spec_check_pre} \npushd %{buildsubdir} \n%define perl_br_testdir %{buildroot}%{perl_testdir}/%{cpan_dist_name} \n%{__mkdir_p} %{perl_br_testdir} \n%{__tar} -cf - %{__perl_test_dirs} | ( cd %{perl_br_testdir} && %{__tar} -xf - ) \nfind . -maxdepth 1 -type f -name '*META*' -exec %{__cp} -vp {} %{perl_br_testdir} ';' \nfind %{perl_br_testdir} -type f -exec %{__chmod} -c -x {} ';' \nT_FILES=`find %{perl_br_testdir} -type f -name '*.t'` \n%fix_shbang_line $T_FILES \n%{__chmod} +x $T_FILES \n%{_fixperms} %{perl_br_testdir} \npopd \n}",
    "__plugindir": "%{_libdir}/rpm-plugins",
    "__pypi_default_extension": "tar.gz",
    "__pypi_url": "https://files.pythonhosted.org/packages/source/",
    "__python": "/usr/bin/python",
    "__python2": "/usr/bin/python2",
    "__python3": "/usr/bin/python3",
    "__python3_other": "/bin/true",
    "__quilt": "/usr/bin/quilt",
    "__rm": "/usr/bin/rm",
    "__scm": "patch",
    "__scm_apply_bzr(qp:m:)": "%{__patch} %{-p:-p%{-p*}} %{-q:-s}\n%{__bzr} commit %{-q} -m %{-m*}",
    "__scm_apply_gendiff(qp:m:)": "%{__patch} %{-p:-p%{-p*}} %{-q:-s} --fuzz=%{_default_patch_fuzz} %{_default_patch_flags} -b --suffix \".%{2}\"",
    "__scm_apply_git(qp:m:)": "%{__git} apply --index --reject %{-p:-p%{-p*}} -\n%{__git} commit %{-q} -m %{-m*} --author \"%{__scm_author}\"",
    "__scm_apply_git_am(qp:m:)": "%{__git} am --reject %{-q} %{-p:-p%{-p*}}",
    "__scm_apply_hg(qp:m:)": "%{__hg} import - %{-p:-p%{-p*}} %{-q} -m %{-m*} --user \"%{__scm_author}\"",
    "__scm_apply_patch(qp:m:)": "%{__patch} %{-p:-p%{-p*}} %{-q:-s} --fuzz=%{_default_patch_fuzz} %{_default_patch_flags}",
    "__scm_apply_quilt(qp:m:)": "%{__quilt} import %{-p:-p%{-p*}} %{1} && %{__quilt} push %{-q}",
    "__scm_author": "%{__scm_username} %{__scm_usermail}",
    "__scm_setup_bzr(q)": "%{__bzr} init %{-q}\n%{__bzr} whoami --branch \"%{__scm_author}\"\n%{__bzr} add .\n%{__bzr} commit %{-q} -m \"%{NAME}-%{VERSION} base\"",
    "__scm_setup_gendiff(q)": "%{nil}",
    "__scm_setup_git(q)": "%{__git} init %{-q}\n%{__git} config user.name \"%{__scm_username}\"\n%{__git} config user.email \"%{__scm_usermail}\"\n%{__git} config gc.auto 0\n%{__git} add --force .\n%{__git} commit %{-q} --allow-empty -a\\\n\t--author \"%{__scm_author}\" -m \"%{NAME}-%{VERSION} base\"",
    "__scm_setup_git_am(q)": "%{expand:%__scm_setup_git %{-q}}",
    "__scm_setup_hg(q)": "%{__hg} init %{-q} .\n%{__hg} add %{-q} .\n%{__hg} commit %{-q} --user \"%{__scm_author}\" -m \"%{NAME}-%{VERSION} base\"",
    "__scm_setup_patch(q)": "%{nil}",
    "__scm_setup_quilt(q)": "%{nil}",
    "__scm_usermail": "<rpm-build>",
    "__scm_username": "rpm-build",
    "__sed": "/usr/bin/sed",
    "__spec_build_args": "%{___build_args}",
    "__spec_build_body": "%{___build_body}",
    "__spec_build_cmd": "%{___build_cmd}",
    "__spec_build_post": "%{___build_post}",
    "__spec_build_pre": "%{___build_pre}",
    "__spec_build_shell": "%{___build_shell}",
    "__spec_build_template": "#!%{__spec_build_shell}\n%{__spec_build_pre}\n%{nil}",
    "__spec_buildrequires_args": "%{___build_args}",
    "__spec_buildrequires_body": "%{___build_body}",
    "__spec_buildrequires_cmd": "%{___build_cmd}",
    "__spec_buildrequires_post": "%{___build_post}",
    "__spec_buildrequires_pre": "%{___build_pre}",
    "__spec_buildrequires_shell": "%{___build_shell}",
    "__spec_buildrequires_template": "#!%{__spec_buildrequires_shell}\n%{__spec_buildrequires_pre}\n%{nil}",
    "__spec_check_args": "%{___build_args}",
    "__spec_check_body": "%{___build_body}",
    "__spec_check_cmd": "%{___build_cmd}",
    "__spec_check_post": "%{___build_post}",
    "__spec_check_pre": "%{___build_pre}",
    "__spec_check_shell": "%{___build_shell}",
    "__spec_check_template": "#!%{__spec_check_shell}\n%{__spec_check_pre}\n%{nil}",
    "__spec_clean_args": "%{___build_args}",
    "__spec_clean_body": "%{___build_body}",
    "__spec_clean_cmd": "%{___build_cmd}",
    "__spec_clean_post": "%{___build_post}",
    "__spec_clean_pre": "%{___build_pre}",
    "__spec_clean_shell": "%{___build_shell}",
    "__spec_clean_template": "#!%{__spec_clean_shell}\n%{__spec_clean_pre}\n%{nil}",
    "__spec_install_args": "%{___build_args}",
    "__spec_install_body": "%{___build_body}",
    "__spec_install_cmd": "%{___build_cmd}",
    "__spec_install_post": "%{?__debug_package:%{__debug_install_post}}\n    %{__arch_install_post}\n    %{__os_install_post}\n%{nil}",
    "__spec_install_pre": "%{___build_pre}\n    [ \"$RPM_BUILD_ROOT\" != \"/\" ] && rm -rf \"${RPM_BUILD_ROOT}\"\n    mkdir -p `dirname \"$RPM_BUILD_ROOT\"`\n    mkdir \"$RPM_BUILD_ROOT\"\n%{nil}",
    "__spec_install_shell": "%{___build_shell}",
    "__spec_install_template": "#!%{__spec_install_shell}\n%{__spec_install_pre}\n%{nil}",
    "__spec_prep_args": "%{___build_args}",
    "__spec_prep_body": "%{___build_body}",
    "__spec_prep_cmd": "%{___build_cmd}",
    "__spec_prep_post": "%{___build_post}",
    "__spec_prep_pre": "%{___build_pre}",
    "__spec_prep_shell": "%{___build_shell}",
    "__spec_prep_template": "#!%{__spec_prep_shell}\n%{__spec_prep_pre}\n%{nil}",
    "__spec_rmbuild_args": "%{___build_args}",
    "__spec_rmbuild_body": "%{___build_body}",
    "__spec_rmbuild_cmd": "%{___build_cmd}",
    "__spec_rmbuild_post": "%{___build_post}",
    "__spec_rmbuild_pre": "%{___build_pre}",
    "__spec_rmbuild_shell": "%{___build_shell}",
    "__spec_rmbuild_template": "#!%{__spec_rmbuild_shell}\n%{__spec_rmbuild_pre}\n%{nil}",
    "__strip": "/usr/bin/strip",
    "__systemd_someargs_0(:)": "%{error:The %%%1 macro requires some arguments}",
    "__systemd_twoargs_2": "%{nil}",
    "__tar": "/usr/bin/tar",
    "__transaction_audit": "%{__plugindir}/audit.so",
    "__transaction_dbus_announce": "%{__plugindir}/dbus_announce.so",
    "__transaction_digest_list": "%{__plugindir}/digest_list.so",
    "__transaction_fapolicyd": "%{__plugindir}/fapolicyd.so",
    "__transaction_fsverity": "%{__plugindir}/fsverity.so",
    "__transaction_ima": "%{__plugindir}/ima.so",
    "__transaction_prioreset": "%{__plugindir}/prioreset.so",
    "__transaction_selinux": "%{__plugindir}/selinux.so",
    "__transaction_syslog": "%{__plugindir}/syslog.so",
    "__transaction_systemd_inhibit": "%{__plugindir}/systemd_inhibit.so",
    "__unzip": "/usr/bin/unzip",
    "__urlhelper_proxyopts": "%{?_httpproxy:--proxy %{_httpproxy}%{?_httpport::%{_httpport}}}%{!?_httpproxy:%{nil}}",
    "__urlhelpercmd": "/usr/bin/curl",
    "__urlhelperopts": "--silent --show-error --fail --globoff --location -o",
    "__vsflags": "0xf0000",
    "__xz": "/usr/bin/xz",
    "__zstd": "/usr/bin/zstd",
    "_arch": "x86_64",
    "_binaries_in_noarch_packages_terminate_build": "1",
    "_binary_filedigest_algorithm": "8",
    "_binary_payload": "w2.xzdio",
    "_bindir": "%{_exec_prefix}/bin",
    "_binfmtdir": "/usr/lib/binfmt.d",
    "_build": "%{_host}",
    "_build_alias": "%{_host_alias}",
    "_build_arch": "x86_64",
    "_build_cpu": "%{_host_cpu}",
    "_build_id_links": "none",
    "_build_name_fmt": "%%{ARCH}/%%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm",
    "_build_os": "%{_host_os}",
    "_build_vendor": "%{_host_vendor}",
    "_builddir": "%{_topdir}/BUILD",
    "_buildrootdir": "%{_topdir}/BUILDROOT",
    "_buildshell": "/bin/sh",
    "_changelog_trimage": "0",
    "_changelog_trimtime": "%{lua:print(os.time() - 2 * 365 * 86400)}",
    "_color_output": "never",
    "_configure": "./configure",
    "_configure_gnuconfig_hack": "1",
    "_configure_libtool_hardening_hack": "1",
    "_datadir": "%{_datarootdir}",
    "_datarootdir": "%{_prefix}/share",
    "_db_backend": "ndb",
    "_dbpath": "%{_var}/lib/rpm",
    "_dbpath_rebuild": "%{_dbpath}",
    "_debuginfo_template": "%package debuginfo\nSummary: Debug information for package %{name}\nGroup: Development/Debug\nAutoReq: 0\nAutoProv: 1\n%description debuginfo\nThis package provides debug information for package %{name}.\nDebug information is useful when developing applications that use this\npackage or when debugging this package.\n%files debuginfo -f debugfiles.list\n%{nil}",
    "_debugsource_packages": "1",
    "_debugsource_template": "%package debugsource\nSummary: Debug sources for package %{name}\nGroup: Development/Debug\nAutoReqProv: 0\n%description debugsource\nThis package provides debug sources for package %{name}.\nDebug sources are useful when developing applications that use this\npackage or when debugging this package.\n%files debugsource -f debugsourcefiles.list\n%{nil}",
    "_default_patch_flags": "--no-backup-if-mismatch -f",
    "_default_patch_fuzz": "0",
    "_defaultdocdir": "%{_datadir}/doc",
    "_defaultlicensedir": "%{_datadir}/licenses",
    "_disable_source_fetch": "1",
    "_docdir_fmt": "%%{NAME}",
    "_duplicate_files_terminate_build": "0",
    "_efi_srpm_macros_setup": "%{expand:%{lua:\n  -- test if our arch matches\n  local function arch(archmacro)\n    local target = rpm.expand(\" %{_target_cpu} \")\n    local arches = rpm.expand(\" \" .. archmacro .. \" \")\n    local match = string.match(arches, target)\n    return (match ~= nil)\n  end\n  -- give us the arch...\n  local function getarch()\n    if arch(\"ia64\") then\n      return(\"ia64\")\n    elseif arch(\"x86_64\") then\n      return(\"x64\")\n    elseif arch(\"%{ix86}\") then\n      return(\"ia32\")\n    elseif arch(\"aarch64\") then\n      return(\"aa64\")\n    elseif arch(\"%{arm}\") then\n      return(\"arm\")\n    else\n      return(\"none\")\n    end\n  end\n  -- alt arch\n  local function getaltarch()\n    if arch(\"x86_64\") then\n      return(\"ia32\")\n    else\n      return(\"none\")\n    end\n  end\n  -- make some macros\n  local done = rpm.expand(\"%{?_efi}\")\n  if done == nil or done == \"\" then\n    local arch = getarch()\n    local alt = getaltarch()\n    print(\"%global _efi x86_64 aarch64\\n\")\n    print(\"%global _efi_vendor openEuler\\n\")\n    if arch == \"none\" then\n      print(\"%global _efi_has_arch 0\\n\")\n    else\n      print(\"%global _efi_has_arch 1\\n\")\n    end\n    print(\"%global _efi_arch \" .. getarch() .. \"\\n\")\n    print(\"%global _efi_arch_upper \" .. string.upper(getarch()) .. \"\\n\")\n    if alt == \"none\" then\n      print(\"%global _efi_has_alt_arch 0\\n\")\n    else\n      print(\"%global _efi_has_alt_arch 1\\n\")\n    end\n    print(\"%global _efi_alt_arch \" .. alt .. \"\\n\")\n    print(\"%global _efi_alt_arch_upper \" .. string.upper(alt) .. \"\\n\")\n  end\n}}",
    "_empty_manifest_terminate_build": "1",
    "_enable_debug_packages": "1",
    "_environmentdir": "/usr/lib/environment.d",
    "_environmnentdir": "%{warn:Use %%_environmentdir instead}%_environmentdir",
    "_exec_prefix": "%{_prefix}",
    "_fileattrsdir": "%{_rpmconfigdir}/fileattrs",
    "_fixperms": "%{__chmod} -Rf a+rX,u+w,g-w,o-w",
    "_fmoddir": "%{_libdir}/gfortran/modules",
    "_fs_build": "1",
    "_fs_cflags": "%{?_fs_build:%{_fs_pre_cflags}}",
    "_fs_pre_cflags": "-specs=/usr/lib/rpm/generic-fs-cc1",
    "_gnu": "-gnu",
    "_hardened_build": "1",
    "_hardened_cflags": "%{?_hardened_build:%{_hardening_cflags}}",
    "_hardened_ldflags": "%{?_hardened_build:%{_hardening_ldflags}}",
    "_hardening_cflags": "-specs=/usr/lib/rpm/generic-hardened-cc1",
    "_hardening_ldflags": "-Wl,-z,now -specs=/usr/lib/rpm/generic-hardened-ld",
    "_hkp_keyserver": "http://pgp.mit.edu",
    "_hkp_keyserver_query": "%{_hkp_keyserver}:11371/pks/lookup?op=get&search=0x",
    "_host": "x86_64-openEuler-linux-gnu",
    "_host_alias": "x86_64-openEuler-linux-gnu%{nil}",
    "_host_cpu": "x86_64",
    "_host_os": "linux",
    "_host_vendor": "openEuler",
    "_include_gdb_index": "1",
    "_includedir": "%{_prefix}/include",
    "_infodir": "%{_datarootdir}/info",
    "_initddir": "%{_sysconfdir}/rc.d/init.d",
    "_initrddir": "%{_initddir}",
    "_install_langs": "all",
    "_install_script_path": "/sbin:/bin:/usr/sbin:/usr/bin:/usr/X11R6/bin",
    "_invalid_encoding_terminates_build": "1",
    "_isa": "%{?__isa:(%{__isa})}%{!?__isa:%{nil}}",
    "_journalcatalogdir": "/usr/lib/systemd/catalog",
    "_keyring": "rpmdb",
    "_keyringpath": "%{_dbpath}/pubkeys/",
    "_ld_as_needed_flags": "%{?_ld_as_needed:-Wl,--as-needed}",
    "_ld_symbols_flags": "%{?_ld_strict_symbol_defs:-Wl,-z,defs}",
    "_lib": "lib64",
    "_libdir": "%{_prefix}/lib64",
    "_libexecdir": "%{_exec_prefix}/libexec",
    "_localstatedir": "/var",
    "_make_output_sync": "%(! %{__make} --version -O >/dev/null 2>&1 || echo -O)",
    "_make_verbose": "V=1 VERBOSE=1",
    "_mandir": "%{_datarootdir}/man",
    "_metainfodir": "%{_datadir}/metainfo",
    "_missing_build_ids_terminate_build": "1",
    "_missing_doc_files_terminate_build": "1",
    "_modprobedir": "/usr/lib/modprobe.d",
    "_modulesloaddir": "/usr/lib/modules-load.d",
    "_monodir": "%{_prefix}/lib/mono",
    "_monogacdir": "%{_monodir}/gac",
    "_oldincludedir": "/usr/include",
    "_os": "linux",
    "_pie_build": "1",
    "_pie_cflags": "%{?_sec_opt_build:?_pie_build:%{_pie_pre_cflags}}",
    "_pie_ldflags": "%{?_sec_opt_build:?_pie_build:%{_pie_pre_ldflags}}",
    "_pie_pre_cflags": "-specs=/usr/lib/rpm/generic-pie-cc1",
    "_pie_pre_ldflags": "-Wl,-z,now -specs=/usr/lib/rpm/generic-pie-ld",
    "_pkgdocdir": "%{_docdir}/%{name}",
    "_pkgverify_flags": "0x0",
    "_pkgverify_level": "digest",
    "_prefix": "/usr",
    "_presetdir": "/usr/lib/systemd/system-preset",
    "_python_bytecompile_errors_terminate_build": "1",
    "_python_bytecompile_extra": "1",
    "_query_all_fmt": "%%{nvra}",
    "_query_selector_match": "default",
    "_rpmconfigdir": "%{getconfdir}",
    "_rpmdir": "%{_topdir}/RPMS",
    "_rpmfilename": "%{_build_name_fmt}",
    "_rpmlock_path": "%{_dbpath}/.rpm.lock",
    "_rpmluadir": "%{_rpmconfigdir}/lua",
    "_rpmmacrodir": "%{_rpmconfigdir}/macros.d",
    "_rundir": "/run",
    "_sbindir": "%{_exec_prefix}/sbin",
    "_sec_opt_build": "1",
    "_sharedstatedir": "/var/lib",
    "_smp_build_ncpus": "%([ -z \"$RPM_BUILD_NCPUS\" ] \\\n\t&& RPM_BUILD_NCPUS=\"%{getncpus}\"; \\\n        ncpus_max=%{?_smp_ncpus_max}; \\\n        if [ -n \"$ncpus_max\" ] && [ \"$ncpus_max\" -gt 0 ] && [ \"$RPM_BUILD_NCPUS\" -gt \"$ncpus_max\" ]; then RPM_BUILD_NCPUS=\"$ncpus_max\"; fi; \\\n        echo \"$RPM_BUILD_NCPUS\";)",
    "_smp_build_nthreads": "%{_smp_build_ncpus}",
    "_smp_mflags": "-j%{_smp_build_ncpus}",
    "_source_filedigest_algorithm": "8",
    "_sourcedir": "%{_topdir}/SOURCES",
    "_specdir": "%{_topdir}/SPECS",
    "_srcrpmdir": "%{_topdir}/SRPMS",
    "_sysconfdir": "/etc",
    "_sysctldir": "/usr/lib/sysctl.d",
    "_systemd_system_env_generator_dir": "/usr/lib/systemd/system-environment-generators",
    "_systemd_user_env_generator_dir": "/usr/lib/systemd/user-environment-generators",
    "_systemd_util_dir": "/usr/lib/systemd",
    "_systemdgeneratordir": "/usr/lib/systemd/system-generators",
    "_systemdusergeneratordir": "/usr/lib/systemd/user-generators",
    "_systemtap_datadir": "/usr/share/systemtap",
    "_systemtap_tapsetdir": "/usr/share/systemtap/tapset",
    "_sysusersdir": "/usr/lib/sysusers.d\n-11: _target\tx86_64-linux",
    "_target_alias": "%{_host_alias}\n-11= _target_cpu\tx86_64\n-11= _target_os\tlinux",
    "_target_platform": "%{_target_cpu}-%{_vendor}-%{_target_os}%{?_gnu}",
    "_target_vendor": "%{_host_vendor}",
    "_tmpfilesdir": "/usr/lib/tmpfiles.d",
    "_tmppath": "%{_var}/tmp",
    "_topdir": "%{getenv:HOME}/rpmbuild",
    "_transaction_color": "3",
    "_udevhwdbdir": "/usr/lib/udev/hwdb.d",
    "_udevrulesdir": "/usr/lib/udev/rules.d",
    "_unique_build_ids": "1",
    "_unique_debug_names": "1",
    "_unique_debug_srcs": "1",
    "_unitdir": "/usr/lib/systemd/system",
    "_unpackaged_files_terminate_build": "1",
    "_update_config_guess": "[ \"%_configure_gnuconfig_hack\" = 1 ] && for i in $(find . -name config.guess) ; do \n      [ -f /usr/lib/rpm/%{_vendor}/$(basename $i) ] && \n      %{__rm} -f $i && \n      %{__cp} -fv /usr/lib/rpm/%{_vendor}/$(basename $i) $i ; \n  done ;",
    "_update_config_sub": "[ \"%_configure_gnuconfig_hack\" = 1 ] && for i in $(find . -name config.sub) ; do \n      [ -f /usr/lib/rpm/%{_vendor}/$(basename $i) ] && \n      %{__rm} -f $i && \n      %{__cp} -fv /usr/lib/rpm/%{_vendor}/$(basename $i) $i ; \n  done ;",
    "_urlhelper": "%{__urlhelpercmd} %{?__urlhelper_localopts} %{?__urlhelper_proxyopts} %{__urlhelperopts}",
    "_use_internal_dependency_generator": "1",
    "_userpresetdir": "/usr/lib/systemd/user-preset",
    "_userunitdir": "/usr/lib/systemd/user",
    "_usr": "/usr",
    "_usrsrc": "%{_usr}/src",
    "_var": "/var",
    "_vendor": "openEuler",
    "_vpath_builddir": "%_target_platform",
    "_vpath_srcdir": ".",
    "_vsflags_build": "%{__vsflags}",
    "_vsflags_erase": "%{__vsflags}",
    "_vsflags_install": "%{__vsflags}",
    "_vsflags_query": "%{__vsflags}",
    "_vsflags_rebuilddb": "0xc0c00",
    "_vsflags_verify": "%{__vsflags}",
    "_wrong_version_format_terminate_build": "1",
    "alpha": "alpha alphaev56 alphaev6 alphaev67",
    "arm": "%{arm32}",
    "arm32": "armv3l armv4b armv4l armv4tl armv5tl armv5tel armv5tejl armv6l armv6hl armv7l armv7hl armv7hnl armv8l armv8hl armv8hnl armv8hcnl",
    "arm64": "aarch64",
    "autopatch(vp:m:M:)": "%{lua:\nif #arg == 0 then\n    local lo = tonumber(rpm.expand(\"%{-m:%{-m*}}\"))\n    local hi = tonumber(rpm.expand(\"%{-M:%{-M*}}\"))\n    for i, n in ipairs(patch_nums) do\n        if ((not lo or n >= lo) and (not hi or n <= hi)) then\n            table.insert(arg, n)\n        end\n    end\nend\nlocal options = rpm.expand(\"%{!-v:-q} %{-p:-p%{-p*}} \")\nlocal bynum = {}\nfor i, p in ipairs(patches) do\n    bynum[patch_nums[i]] = p\nend\nfor i, a in ipairs(arg) do\n    local p = bynum[a]\n    if p then\n        print(rpm.expand(\"%__apply_patch -m %{basename:\"..p..\"}  \"..options..p..\" \"..i..\"\\n\"))\n    else\n        macros.error({\"no such patch \"..a})\n    end\nend\n}",
    "autosetup(a:b:cDn:TvNS:p:)": "%setup %{-a} %{-b} %{-c} %{-D} %{-n} %{-T} %{!-v:-q}\n%{-S:%global __scm %{-S*}}\n%{expand:%__scm_setup_%{__scm} %{!-v:-q}}\n%{!-N:%autopatch %{-v} %{-p:-p%{-p*}}}",
    "bcond_with": "%{expand:%%{?_with_%{1}:%%global with_%{1} 1}}",
    "bcond_without": "%{expand:%%{!?_without_%{1}:%%global with_%{1} 1}}",
    "binfmt_apply": "%{expand:%%{?__systemd_someargs_%#:%%__systemd_someargs_%# binfmt_apply}} \n[ -x /usr/lib/systemd/systemd-binfmt ] && /usr/lib/systemd/systemd-binfmt %{?*} || : \n%{nil}",
    "build_cflags": "%{optflags}",
    "build_cxxflags": "%{optflags} -fexceptions",
    "build_fflags": "%{optflags} -fexceptions -I%{_fmoddir}",
    "build_ldflags": "-Wl,-z,relro %{_ld_as_needed_flags} %{_ld_symbols_flags} %{_hardened_ldflags}",
    "buildroot": "%{_buildrootdir}/%{NAME}-%{VERSION}-%{RELEASE}.%{_arch}",
    "chrpath_delete": "find $RPM_BUILD_ROOT/ -type f -exec file {} ';' | grep \"<ELF>\" | awk -F ':' '{print $1}' | xargs -i chrpath --delete {}",
    "clamp_mtime_to_source_date_epoch": "0",
    "configure": "%{set_build_flags}; \n  [ \"%_configure_gnuconfig_hack\" = 1 ] && for i in $(find $(dirname %{_configure}) -name config.guess -o -name config.sub) ; do \n      [ -f /usr/lib/rpm/%{_vendor}/$(basename $i) ] && %{__rm} -f $i && %{__cp} -fv /usr/lib/rpm/%{_vendor}/$(basename $i) $i ; \n  done ; \n  [ \"%_configure_libtool_hardening_hack\" = 1 ] && [ x != \"x%{_hardened_ldflags}\" ] && \n      for i in $(find . -name ltmain.sh) ; do \n        %{__sed} -i.backup -e 's~compiler_flags=$~compiler_flags=\"%{_hardened_ldflags}\"~' $i \n      done ; \n  %{_configure} --build=%{_build} --host=%{_host} \\\n\t--program-prefix=%{?_program_prefix} \\\n\t--disable-dependency-tracking \\\n\t%{?_configure_disable_silent_rules:--disable-silent-rules} \\\n\t--prefix=%{_prefix} \\\n\t--exec-prefix=%{_exec_prefix} \\\n\t--bindir=%{_bindir} \\\n\t--sbindir=%{_sbindir} \\\n\t--sysconfdir=%{_sysconfdir} \\\n\t--datadir=%{_datadir} \\\n\t--includedir=%{_includedir} \\\n\t--libdir=%{_libdir} \\\n\t--libexecdir=%{_libexecdir} \\\n\t--localstatedir=%{_localstatedir} \\\n\t--sharedstatedir=%{_sharedstatedir} \\\n\t--mandir=%{_mandir} \\\n\t--infodir=%{_infodir}",
    "cpan_dist_name": "%(eval echo %{name} | %{__sed} -e 's/^perl-//')",
    "debug_package": "%ifnarch noarch\n%global __debug_package 1\n%_debuginfo_template\n%{?_debugsource_packages:%_debugsource_template}\n%endif\n%{nil}",
    "defined": "%{expand:%%{?%{1}:1}%%{!?%{1}:0}}",
    "delete_la": "find $RPM_BUILD_ROOT -type f -name \"*.la\" -delete",
    "delete_la_and_a": "find $RPM_BUILD_ROOT -type f -name \"*.la\" -delete \nfind $RPM_BUILD_ROOT -type f -name \"*.a\" -delete",
    "disable_rpath": "sed -i 's|^hardcode_libdir_flag_spec=.*|hardcode_libdir_flag_spec=\"\"|g' libtool \nsed -i 's|^runpath_var=LD_RUN_PATH|runpath_var=DIE_RPATH_DIE|g' libtool",
    "dist": "%{nil}",
    "efi": "%{expand:%{_efi_srpm_macros_setup}}%{expand:%{_efi}}",
    "efi_alt_arch": "%{expand:%{_efi_srpm_macros_setup}}%{?_efi_alt_arch}%{nil}",
    "efi_alt_arch_upper": "%{expand:%{_efi_srpm_macros_setup}}%{?_efi_alt_arch_upper}%{nil}",
    "efi_arch": "%{expand:%{_efi_srpm_macros_setup}}%{_efi_arch}",
    "efi_arch_upper": "%{expand:%{_efi_srpm_macros_setup}}%{_efi_arch_upper}",
    "efi_build_requires": "bash coreutils",
    "efi_esp_boot": "%{efi_esp_efi}/BOOT",
    "efi_esp_dir": "%{expand:%{_efi_srpm_macros_setup}}%{efi_esp_efi}/%{efi_vendor}",
    "efi_esp_efi": "%{efi_esp_root}/EFI",
    "efi_esp_root": "/boot/efi",
    "efi_has_alt_arch": "%{expand:%{_efi_srpm_macros_setup}}0%{_efi_has_alt_arch}",
    "efi_has_arch": "%{expand:%{_efi_srpm_macros_setup}}0%{_efi_has_arch}",
    "efi_srpm_macros_version": "%{expand:%{_efi_srpm_macros_setup}}4",
    "efi_vendor": "%{expand:%{_efi_srpm_macros_setup}}%{expand:%{_efi_vendor}}",
    "filter_from_provides": "%{expand:\n%global __filter_from_prov %{?__filter_from_prov} | %{__sed} -e '%*' \n}",
    "filter_from_requires": "%{expand:\n%global __filter_from_req %{?__filter_from_req} | %{__sed} -e '%*' \n}",
    "filter_provides_in(P)": "%{expand:\n%global __filter_prov_cmd %{?__filter_prov_cmd} %{__grep} -v %{-P} '%*' | \n}",
    "filter_requires_in(P)": "%{expand:\n%global __filter_req_cmd %{?__filter_req_cmd} %{__grep} -v %{-P} '%*' | \n}",
    "filter_setup": "%{expand:\n%global _use_internal_dependency_generator 0 \n%global __deploop() while read FILE; do echo \"${FILE}\" | /usr/lib/rpm/rpmdeps -%{1}; done | /bin/sort -u \n%global __find_provides /bin/sh -c \"%{?__filter_prov_cmd} %{__deploop P} %{?__filter_from_prov}\" \n%global __find_requires /bin/sh -c \"%{?__filter_req_cmd}  %{__deploop R} %{?__filter_from_req}\" \n}",
    "find_lang": "%{_rpmconfigdir}/find-lang.sh %{buildroot}",
    "fix_shbang_line": "TMPHEAD=`mktemp`\nTMPBODY=`mktemp`\nfor file in %* ; do \n    head -1 $file > $TMPHEAD\n    tail -n +2 $file > $TMPBODY\n    %{__perl} -pi -e '$f = /^#!/ ? \"\" : \"#!%{__perl}$/\"; $_=\"$f$_\"' $TMPHEAD\n    cat $TMPHEAD $TMPBODY > $file\ndone\n%{__perl} -MExtUtils::MakeMaker -e \"ExtUtils::MM_Unix->fixin(qw{%*})\"\n%{__rm} $TMPHEAD $TMPBODY\n%{nil}",
    "forgeautosetup(a:b:cDn:TvNS:p:)": "%autosetup %{?forgesetupargs} %{-a} %{-b} %{-c} %{-D} %{-n} %{-T} %{-v} %{-N} %{-S} %{-p}",
    "forgemeta(u:spvi)": "%{lua:\nlocal forgeurl    = rpm.expand(\"%{?-u*}\")\nif (forgeurl == \"\") then\n  forgeurl        = rpm.expand(\"%{?forgeurl}\")\nend\nlocal silent      = false\nlocal verbose     = false\nlocal informative = false\nif (rpm.expand(\"%{?-s}\") ~= \"\") then\n  silent          = true\nend\nif (rpm.expand(\"%{?-p}\") ~= \"\") then\n  silent          = false\nend\nif (rpm.expand(\"%{?-v}\") ~= \"\") then\n  verbose         = true\nend\nif (rpm.expand(\"%{?-i}\") ~= \"\") then\n  informative     = true\nend\nlocal tag         = rpm.expand(\"%{?tag}\")\nlocal commit      = rpm.expand(\"%{?commit}\")\n-- Be explicit about the spec variables we鈥檙e setting\nlocal function explicitset(rpmvariable,value)\n  rpm.define(rpmvariable .. \" \" .. value)\n  if verbose then\n    rpm.expand(\"%{echo:Setting %%{\" .. rpmvariable .. \"} = \" .. value .. \"\\n}\")\n  end\nend\n-- Never ever stomp on a spec variable the packager already set\nlocal function safeset(rpmvariable,value)\n  if (rpm.expand(\"%{?\" .. rpmvariable .. \"}\") == \"\") then\n    explicitset(rpmvariable,value)\n  end\nend\n-- Set spec variable values for each known software publishing service\nif (forgeurl ~= \"\") then\n  local forge          = string.match(forgeurl, \"^[^:]+://([^/]+)/\")\n  if (forge == nil) then\n    if not silent then\n      rpm.expand(\"%{error:URLs must include a protocol such as https:// and a path starting with / !\\n}\")\n    end\n  else\n    if (string.match(forge, \"^gitlab[%.-]\") or string.match(forge, \"[%.-]gitlab[%.]\")) then\n      forgeurl = string.match(forgeurl, \"https://[^/]+/[^/]+/[^/#?]+\")\n      if (forgeurl == nil) then\n        if not silent then\n          rpm.expand(\"%{error:Gitlab URLs must match https://(鈥-.])gitlab[-.]鈥/owner/repo !\\n}\")\n        end\n      else\n        explicitset(\"forgeurl\",   forgeurl)\n        if (commit == \"\") then\n          rpm.expand(\"%{error:All Gitlab URLs require commit value knowledge: you need to define %{commit}!\\nPlease vote on https://gitlab.com/gitlab-org/gitlab-ce/issues/38830\\n}\")\n        end\n        safeset(\"archiveext\",     \"tar.bz2\")\n        safeset(\"forgesetupargs\", \"-n %{archivename}\")\n        if (commit ~= \"\") or (tag ~= \"\") then\n          safeset(\"scm\", \"git\")\n        end\n        local owner   = string.match(forgeurl, \"^[^:]+://[^/]+/([^/]+)\")\n        local repo    = string.match(forgeurl, \"^[^:]+://[^/]+/[^/]+/([^/]+)\")\n        local version = rpm.expand(\"%{?version}\")\n        if (version ~= \"\") and (version ~= \"0\") and (tag == \"\") then\n          -- GitLab does not have strong versionning semantics\n          -- Some projects use \"version\" as release tag, others \"v\" + \"version\"\n          -- Tag value needs to be explicitly declared before calling the macro\n          -- in the second case\n          tag = version\n          safeset(\"tag\", tag)\n        end\n        if (tag ~= \"\") then\n          safeset(\"archivename\", repo .. \"-%{tag}-%{commit}\")\n          safeset(\"archiveurl\",  \"%{forgeurl}/repository/%{tag}/archive.%{archiveext}\")\n        else\n          safeset(\"archivename\", repo .. \"-%{commit}\")\n          safeset(\"archiveurl\",  \"%{forgeurl}/repository/%{commit}/archive.%{archiveext}\")\n        end\n      end\n    end\n    if (string.match(forge, \"^github[%.-]\") or string.match(forge, \"[%.-]github[%.]\")) then\n      forgeurl = string.match(forgeurl, \"https://[^/]+/[^/]+/[^/#?]+\")\n      if (forgeurl == nil) then\n        if not silent then\n          rpm.expand(\"%{error:GitHub URLs must match https://(鈥-.])github[-.]鈥/owner/repo !\\n}\")\n        end\n      else\n        explicitset(\"forgeurl\",   forgeurl)\n        safeset(\"archiveext\",     \"tar.gz\")\n        local forgesetupargs = \"-n %{archivename}\"\n        if (commit ~= \"\") or (tag ~= \"\") then\n          safeset(\"scm\", \"git\")\n        end\n        local owner = string.match(forgeurl, \"^[^:]+://[^/]+/([^/]+)\")\n        local repo  = string.match(forgeurl, \"^[^:]+://[^/]+/[^/]+/([^/]+)\")\n        if (tag ~= \"\") then\n          -- if upstream used a version suffix such as -rc1 or -beta it will not\n          -- be a valid version string for rpm but github will accept it fine and\n          -- use the same naming as for other versions: v prefix in the tag and\n          -- archivename, no v prefix in the topdir naming inside the archive\n          local version = rpm.expand(\"%{?version}\")\n          if version ~= \"\" and\n             (string.match(tag, \"^v\" .. version .. \"[^%d]\") or\n              string.match(tag, \"^v\" .. version .. \"$\"))    then\n            forgesetupargs = \"-n \" .. repo .. \"-\" .. string.gsub(tag, \"^v\", \"\")\n          end\n          safeset(\"archivename\",   repo .. \"-%{tag}\")\n          safeset(\"archiveurl\",    \"%{forgeurl}/archive/%{tag}.%{archiveext}\")\n        else\n          if (commit ~= \"\") then\n            safeset(\"archivename\", repo .. \"-%{commit}\")\n            safeset(\"archiveurl\",  \"%{forgeurl}/archive/%{commit}/\" .. repo .. \"-%{commit}.%{archiveext}\")\n          else\n            safeset(\"archivename\", repo .. \"-%{version}\")\n            safeset(\"archiveurl\",   \"%{forgeurl}/archive/v%{version}.%{archiveext}\")\n          end\n        end\n        safeset(\"forgesetupargs\", forgesetupargs)\n      end\n    end\n    if (forge == \"code.googlesource.com\") then\n      forgeurl = string.match(forgeurl, \"https://code.googlesource.com/[^#?]*[^/#?]+\")\n      if (forgeurl == nil) then\n        if not silent then\n          rpm.expand(\"%{error:Googlesource URLs must match https://code.googlesource.com/鈥/repo !\\n}\")\n        end\n      else\n        explicitset(\"forgeurl\",   forgeurl)\n        safeset(\"archiveext\",     \"tar.gz\")\n        safeset(\"forgesetupargs\", \"-c\")\n        if (commit ~= \"\") or (tag ~= \"\") then\n          safeset(\"scm\", \"git\")\n        end\n        local repo = string.match(forgeurl, \"^[^:]+://.+/([^/?#]+)\")\n        if (tag ~= \"\") then\n          safeset(\"archivename\",   repo .. \"-%{tag}\")\n          safeset(\"archiveurl\",    \"%{forgeurl}/+archive/%{tag}.%{archiveext}\")\n        else\n          if (commit ~= \"\") then\n            safeset(\"archivename\", repo .. \"-%{commit}\")\n            safeset(\"archiveurl\",  \"%{forgeurl}/+archive/%{commit}.%{archiveext}\")\n          else\n            safeset(\"archivename\", repo .. \"-v%{version}\")\n            safeset(\"archiveurl\",  \"%{forgeurl}/+archive/v%{version}.%{archiveext}\")\n          end\n        end\n      end\n    end\n    if (forge == \"bitbucket.org\") then\n      forgeurl = string.match(forgeurl, \"https://[^/]+/[^/]+/[^/#?]+\")\n      if (forgeurl == nil) then\n        if not silent then\n          rpm.expand(\"%{error:BitBucket URLs must match https://bitbucket.org/owner/repo !\\n}\")\n        end\n      else\n        explicitset(\"forgeurl\",   forgeurl)\n        if (commit == \"\") then\n          rpm.expand(\"%{error:All BitBucket URLs require commit value knowledge: you need to define %{commit}!\\n}\")\n        end\n        local shortcommit = string.sub(commit, 1, 12)\n        safeset(\"archiveext\", \"tar.bz2\")\n        -- Default to git even though BitBucket allows choosing between several SCMs\n        -- Set scm to hg for example before calling the macro if your project does not use git\n        safeset(\"scm\", \"git\")\n        local owner = string.match(forgeurl, \"^[^:]+://[^/]+/([^/]+)\")\n        local repo  = string.match(forgeurl, \"^[^:]+://[^/]+/[^/]+/([^/]+)\")\n        safeset(\"archivename\",    owner .. \"-\" .. repo .. \"-\" .. shortcommit)\n        safeset(\"forgesetupargs\", \"-n %{archivename}\")\n        if (tag ~= \"\") then\n          safeset(\"archiveurl\",  \"%{forgeurl}/get/%{tag}.%{archiveext}\")\n        else\n          safeset(\"archiveurl\",  \"%{forgeurl}/get/%{commit}.%{archiveext}\")\n        end\n      end\n    end\n    if (forge == \"pagure.io\") then\n      if not silent then\n        rpm.expand(\"%{error:https://pagure.io/pagure/issue/861 needs to be resolved before the 鈥減agure.io鈥漒nsoftware publishing service can be supported.\\n}\")\n      end\n    end\n    -- Final tests to check forgeurl was successfuly parsed\n    if not silent then\n      if (rpm.expand(\"%{?archivename}\") == \"\") or (rpm.expand(\"%{?archiveurl}\") == \"\") then\n        rpm.expand(\"%{error:Automation for the 鈥\" .. forge .. \"鈥漒nsoftware publishing service is not implemented yet.\\nPlease extend the %%forgemeta macro!\\n}\")\n      end\n    end\n  end\nend\n-- Set defaults if forgeurl is missing or does not parse\nlocal archivename = rpm.expand(\"%{?archivename}\")\nsafeset(\"archiveext\",       \"tar.gz\")\nif (archivename ~= \"\") then\n  safeset(\"forgesetupargs\", \"-n %{archivename}\")\nend\nif (commit ~= \"\") or (tag ~= \"\") then\n  safeset(\"scm\",            \"git\")\nend\n-- Source URL processing (computing the forgesource spec variable)\nlocal archiveurl  = rpm.expand(\"%{?archiveurl}\")\nlocal archiveext  = rpm.expand(\"%{?archiveext}\")\nif (archivename ~= \"\") and (archiveurl ~= \"\") then\n  if (string.match(archiveurl, \"/([^/]+)$\") == archivename .. \".\" .. archiveext) then\n    safeset(\"forgesource\", \"%{archiveurl}\")\n  else\n    safeset(\"forgesource\", \"%{?archiveurl}#/%{?archivename}.%{archiveext}\")\n  end\nend\n-- dist processing (computing the correct pefix for snapshots)\nlocal distprefix = rpm.expand(\"%{?tag}\")\nlocal version    = rpm.expand(\"%{?version}\")\nif (distprefix == version) or (distprefix == \"v\" .. version) then\n  distprefix = \"\"\nend\nif (distprefix == \"\") then\n  distprefix = string.sub(rpm.expand(\"%{?commit}\"), 1, 7)\nend\nif (distprefix ~= \"\") then\n  local dist = \".%{?date}%{!?date:%([ -r %{_sourcedir}/%{archivename}.%{archiveext} ] && date +%Y%m%d -u -r %{_sourcedir}/%{archivename}.%{archiveext})}%{scm}\" .. string.gsub(distprefix, \"-\",\".\") .. rpm.expand(\"%{?dist}\")\n  explicitset(\"dist\", dist)\nend\n-- Final spec variable summary if the macro was called with -i\nif informative then\n  rpm.expand(\"%{echo:Forge-specific packaging variables\\n}\")\n  rpm.expand(\"%{echo:  forgeurl:        %{?forgeurl}\\n}\")\n  rpm.expand(\"%{echo:  forgesource:     %{?forgesource}\\n}\")\n  rpm.expand(\"%{echo:  forgesetupargs:  %{?forgesetupargs}\\n}\")\n  rpm.expand(\"%{echo:Generic variables\\n}\")\n  rpm.expand(\"%{echo:  archivename:     %{?archivename}\\n}\")\n  rpm.expand(\"%{echo:  archiveext:      %{?archiveext}\\n}\")\n  rpm.expand(\"%{echo:  archiveurl:      %{?archiveurl}\\n}\")\n  rpm.expand(\"%{echo:  scm:             %{?scm}\\n}\")\n  rpm.expand(\"%{echo:  tag:             %{?tag}\\n}\")\n  rpm.expand(\"%{echo:  commit:          %{?commit}\\n}\")\n  rpm.expand(\"%{echo:  dist:            %{?dist} (snapshot date is either manually supplied or computed once %%{_sourcedir}/%%{archivename}.%%{archiveext} is available)\\n}\")\nend\n}",
    "forgesetup(a:b:cDn:Tq)": "%setup %{?forgesetupargs} %{-a} %{-b} %{-c} %{-D} %{-n} %{-T} %{-q}",
    "fpc_arches": "%{generic_arches}",
    "gccgo_arches": "%{mips}",
    "generic_arches": "%{ix86} x86_64 %{arm} aarch64 sw_64 loongarch64",
    "ghc_arches": "%{generic_arches}",
    "ghc_arches_with_ghci": "%{generic_arches}",
    "go_arches": "%{golang_arches} %{gccgo_arches}",
    "go_compiler": "1",
    "golang_arches": "%{ix86} x86_64 %{arm} aarch64 ppc64le s390x riscv64",
    "gometa(u:spvi)": "%{expand:%{lua:\nlocal forgeurl    = rpm.expand(\"%{?-u*}\")\nif (forgeurl == \"\") then\n  forgeurl        = rpm.expand(\"%{?forgeurl}\")\nend\n-- Be explicit about the spec variables we鈥檙e setting\nlocal function explicitset(rpmvariable,value)\n  rpm.define(rpmvariable .. \" \" .. value)\n  if (rpm.expand(\"%{?-v}\") ~= \"\") then\n    rpm.expand(\"%{echo:Setting %%{\" .. rpmvariable .. \"} = \" .. value .. \"\\n}\")\n  end\nend\n-- Never ever stomp on a spec variable the packager already set\nlocal function safeset(rpmvariable,value)\n  if (rpm.expand(\"%{?\" .. rpmvariable .. \"}\") == \"\") then\n    explicitset(rpmvariable,value)\n  end\nend\n-- All the Go packaging automation relies on goipath being set\nlocal goipath = rpm.expand(\"%{?goipath}\")\nif (goipath == \"\") then\n  rpm.expand(\"%{error:Please set the Go import path in the 鈥済oipath鈥 variable before calling 鈥済ometa鈥!}\")\nend\n-- Compute and set spec variables\nif (forgeurl ~= \"\") then\n  rpm.expand(\"%forgemeta %{?-v} %{?-i} %{?-s} %{?-p} -u \" .. forgeurl .. \"\\n\")\n  safeset(\"gourl\", forgeurl)\nelse\n  safeset(\"gourl\", \"https://\" .. goipath)\n  rpm.expand(\"%forgemeta %{?-v} %{?-i} -s     %{?-p} -u %{gourl}\\n\")\nend\nif (rpm.expand(\"%{?forgesource}\") ~= \"\") then\n  safeset(\"gosource\", \"%{forgesource}\")\nelse\n  safeset(\"gosource\", \"%{gourl}/%{archivename}.%{archiveext}\")\nend\nsafeset(\"goname\", \"%gorpmname %{goipath}\")\nrpm.define(\"gosetup %forgesetup\")\n-- Final spec variable summary if the macro was called with -i\nif (rpm.expand(\"%{?-i}\") ~= \"\") then\n  rpm.expand(\"%{echo:Go-specific packaging variables}\")\n  rpm.expand(\"%{echo:  goipath:         %{?goipath}}\")\n  rpm.expand(\"%{echo:  goname:          %{?goname}}\")\n  rpm.expand(\"%{echo:  gourl:           %{?gourl}}\")\n  rpm.expand(\"%{echo:  gosource:        %{?gosource}}\")\nend}\nBuildRequires: compiler(go-compiler)\nExclusiveArch: %{go_arches}\n}",
    "gopath": "%{_datadir}/gocode",
    "gorpmname": "%{lua:\nlocal goname = rpm.expand(\"%1\")\n-- lowercase and end with '/'\ngoname       = string.lower(goname .. \"/\")\n-- remove eventual protocol prefix\ngoname       = string.gsub(goname, \"^http(s?)://\",         \"\")\n-- remove eventual .git suffix\ngoname       = string.gsub(goname, \"%.git/*\",              \"\")\n-- remove eventual git. prefix\ngoname       = string.gsub(goname, \"^git%.\",              \"\")\n-- add golang prefix\ngoname       = \"golang-\" .. goname\n-- remove FQDN root (.com, .org, etc)\ngoname       = string.gsub(goname, \"^([^/]+)%.([^%./]+)/\", \"%1/\")\n-- special-case x.y.z number-strings as that鈥檚 an exception in our naming\n-- guidelines\nrepeat\n  goname, i = string.gsub(goname, \"(%d)%.(%d)\",            \"%1:%2\")\nuntil i == 0\n-- replace various separators rpm does not like with -\ngoname       = string.gsub(goname, \"[%._/%-]+\",            \"-\")\n-- because of the Azure sdk\ngoname       = string.gsub(goname, \"%-for%-go%-\",          \"-\")\n-- Tokenize along - separators and remove duplicates to avoid\n-- golang-foo-foo-bar-foo names\nlocal result = \"\"\nlocal tokens = {}\ntokens[\"go\"]     = true\nfor token in string.gmatch(goname, \"[^%-]+\") do\n   if not tokens[token] then\n      result = result .. \"-\" .. token\n      tokens[token] = true\n   end\nend\n-- reassemble the string, restore x.y.z runs, convert the vx.y.z\n-- Go convention to x.y.z as prefered in rpm naming\nresult = string.gsub(result, \"^-\", \"\")\nresult = string.gsub(result, \":\", \".\")\n-- some projects have a name that end up in a number, and *also* add release\n-- numbers on top of it, keep a - prefix before version strings\nresult = string.gsub(result, \"%-v([%.%d])\", \"-%1\")\nprint(result)\n}",
    "install": "%{?_enable_debug_packages:%{?buildsubdir:%{debug_package}}}\n%%install\n%{nil}",
    "install_info": "/sbin/install-info %1 %{_infodir}/dir || :",
    "install_info_rm": "/sbin/install-info --remove %1 %{_infodir}/dir || :",
    "ix86": "i386 i486 i586 i686 pentium3 pentium4 athlon geode",
    "journal_catalog_update": "%{nil}",
    "ldc_arches": "%{generic_arches}",
    "ldconfig_post(n:)": "%{?ldconfig:%post -p %ldconfig %{?*} %{-n:-n %{-n*}}\n%end}",
    "ldconfig_postun(n:)": "%{?ldconfig:%postun -p %ldconfig %{?*} %{-n:-n %{-n*}}\n%end}",
    "ldconfig_scriptlets(n:)": "%{?ldconfig:\n%ldconfig_post %{?*} %{-n:-n %{-n*}}\n%ldconfig_postun %{?*} %{-n:-n %{-n*}}\n}",
    "make_build": "%{__make} %{_make_output_sync} %{?_smp_mflags} %{_make_verbose}",
    "make_install": "%{__make} install DESTDIR=%{?buildroot} INSTALL=\"%{__install} -p\"",
    "makeinstall": "echo \"warning: %%makeinstall is deprecated, try %%make_install instead\" 1>&2\n  %{__make} \\\n\tprefix=%{?buildroot:%{buildroot}}%{_prefix} \\\n\texec_prefix=%{?buildroot:%{buildroot}}%{_exec_prefix} \\\n\tbindir=%{?buildroot:%{buildroot}}%{_bindir} \\\n\tsbindir=%{?buildroot:%{buildroot}}%{_sbindir} \\\n\tsysconfdir=%{?buildroot:%{buildroot}}%{_sysconfdir} \\\n\tdatadir=%{?buildroot:%{buildroot}}%{_datadir} \\\n\tincludedir=%{?buildroot:%{buildroot}}%{_includedir} \\\n\tlibdir=%{?buildroot:%{buildroot}}%{_libdir} \\\n\tlibexecdir=%{?buildroot:%{buildroot}}%{_libexecdir} \\\n\tlocalstatedir=%{?buildroot:%{buildroot}}%{_localstatedir} \\\n\tsharedstatedir=%{?buildroot:%{buildroot}}%{_sharedstatedir} \\\n\tmandir=%{?buildroot:%{buildroot}}%{_mandir} \\\n\tinfodir=%{?buildroot:%{buildroot}}%{_infodir} \\\n  install",
    "mips": "%{mips32} %{mips64}",
    "mips32": "mips mipsel mipsr6 mipsr6el",
    "mips64": "mips64 mips64el mips64r6 mips64r6el",
    "mipseb": "mips mipsr6 mips64 mips64r6",
    "mipsel": "mipsel mipsr6el mips64el mips64r6el",
    "mono_arches": "%{generic_arches}",
    "nil": "%{!?nil}",
    "nim_arches": "%{generic_arches}",
    "nodejs_arches": "%{generic_arches}",
    "ocaml_natdynlink": "%{generic_arches}",
    "ocaml_native_compiler": "%{generic_arches}",
    "ocaml_native_profiling": "%{generic_arches}",
    "openEuler": "2",
    "openblas_arches": "%{generic_arches}\n-11: optflags\t%{__global_compiler_flags} -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection",
    "package_help": "%package        help \nSummary:        Documents for %{name} \nBuildarch:      noarch \nRequires:       man info \n\n%description help \nMan pages and other related documents for %{name}.",
    "patches": "%{lua: for i, p in ipairs(patches) do print(p..\" \") end}",
    "perl_archlib": "%(eval \"`%{__perl} -V:installarchlib`\"; echo $installarchlib)",
    "perl_default_filter": "%{expand:\n%global __provides_exclude_from %{?__provides_exclude_from:%__provides_exclude_from|}^%{_docdir}\n%global __requires_exclude_from %{?__requires_exclude_from:%__requires_exclude_from|}^%{_docdir}\n%global __provides_exclude %{?__provides_exclude:%__provides_exclude|}^perl\\\\(VMS|^perl\\\\(Win32|^perl\\\\(DB\\\\)|^perl\\\\(UNIVERSAL\\\\)\n%global __requires_exclude %{?__requires_exclude:%__requires_exclude|}^perl\\\\(VMS|^perl\\\\(Win32\n}",
    "perl_default_filter_revision": "3",
    "perl_default_subpackage_tests": "%perl_subpackage_tests t/",
    "perl_ext_env_unset": "%{expand:\nunset PERL_MM_OPT MODULEBUILDRC PERL5INC\nexport PERL_AUTOINSTALL=\"--defaultdeps\"\nexport PERL_MM_USE_DEFAULT=1\n}",
    "perl_privlib": "%(eval \"`%{__perl} -V:installprivlib`\"; echo $installprivlib)",
    "perl_sitearch": "%(eval \"`%{__perl} -V:installsitearch`\"; echo $installsitearch)",
    "perl_sitelib": "%(eval \"`%{__perl} -V:installsitelib`\"; echo $installsitelib)",
    "perl_subpackage_tests": "%{expand:\n%global __perl_package 1\n%global __perl_test_dirs %* \n%global __spec_check_pre %{expand:%{__perl_check_pre}} \n%package tests\nSummary: Test suite for package %{name}\nGroup: Development/Debug\nRequires: %{name} = %{?epoch:%{epoch}:}%{version}-%{release}\nRequires: /usr/bin/prove \n%{?__tests_spkg_req:Requires: %__tests_spkg_req}\n%{?__tests_spkg_prov:Provides: %__tests_spkg_prov}\nAutoReqProv: 0 \n%description tests\nThis package provides the test suite for package %{name}.\n%files tests\n%defattr(-,root,root,-)\n%{perl_testdir}\n}",
    "perl_testdir": "%{_libexecdir}/perl5-tests",
    "perl_vendorarch": "%(eval \"`%{__perl} -V:installvendorarch`\"; echo $installvendorarch)",
    "perl_vendorlib": "%(eval \"`%{__perl} -V:installvendorlib`\"; echo $installvendorlib)",
    "perl_version": "%(eval \"`%{__perl} -V:version`\"; echo $version)",
    "pkg_vcmp": "(%{expand:%%{pkg_version_cmp %1 %3}} %2 0)",
    "pkg_version": "%(LC_ALL=C rpm -q --whatprovides --qf \"%%{version}\" \"%1\" | sed -e \"s/^no package provides .*/~~~/\")",
    "pkg_version_cmp": "%{expand:%{expand:%%%%{rpm_vercmp %%{pkg_version %1} %%2}}}",
    "power64": "ppc64 ppc64p7 ppc64le",
    "py2_build": "%{expand:\\\n  CFLAGS=\"${CFLAGS:-${RPM_OPT_FLAGS}}\" LDFLAGS=\"${LDFLAGS:-${RPM_LD_FLAGS}}\"\\\n  %{__python2} %{py_setup} %{?py_setup_args} build --executable=\"%{__python2} %{py2_shbang_opts}\" %{?*}\n  sleep 1\n}",
    "py2_build_egg": "%{expand:\\\n  CFLAGS=\"${CFLAGS:-${RPM_OPT_FLAGS}}\" LDFLAGS=\"${LDFLAGS:-${RPM_LD_FLAGS}}\"\\\n  %{__python2} %{py_setup} %{?py_setup_args} bdist_egg %{?*}\n  sleep 1\n}",
    "py2_build_wheel": "%{expand:\\\n  CFLAGS=\"${CFLAGS:-${RPM_OPT_FLAGS}}\" LDFLAGS=\"${LDFLAGS:-${RPM_LD_FLAGS}}\"\\\n  %{__python2} %{py_setup} %{?py_setup_args} bdist_wheel %{?*}\n  sleep 1\n}",
    "py2_dist": "%{lua:\n        args = {}\n        arg = 1\n        while (true) do\n                name = rpm.expand(\"%{?\" .. arg .. \":%{\" .. arg .. \"}}\");\n                if (name == nil or name == '') then\n                        break\n                end\n                args[arg] = name\n                arg = arg + 1\n        end\n        for arg, name in ipairs(args) do\n                canonical = rpm.expand(\"%py_dist_name \" .. name);\n                print(\"python2dist(\" .. canonical .. \") \");\n        end\n}",
    "py2_install": "%{expand:\\\n  CFLAGS=\"${CFLAGS:-${RPM_OPT_FLAGS}}\" LDFLAGS=\"${LDFLAGS:-${RPM_LD_FLAGS}}\"\\\n  %{__python2} %{py_setup} %{?py_setup_args} install -O1 --skip-build --root %{buildroot} %{?*}\n}",
    "py2_install_egg": "%{expand:\\\n  mkdir -p %{buildroot}%{python2_sitelib}\n  easy_install-%{python2_version} -m --prefix %{buildroot}%{_prefix} -Z dist/*-py%{python2_version}.egg %{?*}\n}",
    "py2_install_wheel": "%{expand:\\\n  pip%{python2_version} install -I dist/%{1} --root %{buildroot} --strip-file-prefix %{buildroot} --no-deps\n}",
    "py2_shbang_opts": "-s",
    "py3_build": "%{expand:\\\n  CFLAGS=\"${CFLAGS:-${RPM_OPT_FLAGS}}\" LDFLAGS=\"${LDFLAGS:-${RPM_LD_FLAGS}}\"\\\n  %{__python3} %{py_setup} %{?py_setup_args} build --executable=\"%{__python3} %{py3_shbang_opts}\" %{?*}\n  sleep 1\n}",
    "py3_build_egg": "%{expand:\\\n  CFLAGS=\"${CFLAGS:-${RPM_OPT_FLAGS}}\" LDFLAGS=\"${LDFLAGS:-${RPM_LD_FLAGS}}\"\\\n  %{__python3} %{py_setup} %{?py_setup_args} bdist_egg %{?*}\n  sleep 1\n}",
    "py3_build_wheel": "%{expand:\\\n  CFLAGS=\"${CFLAGS:-${RPM_OPT_FLAGS}}\" LDFLAGS=\"${LDFLAGS:-${RPM_LD_FLAGS}}\"\\\n  %{__python3} %{py_setup} %{?py_setup_args} bdist_wheel %{?*}\n  sleep 1\n}",
    "py3_dist": "%{lua:\n        args = {}\n        arg = 1\n        while (true) do\n                name = rpm.expand(\"%{?\" .. arg .. \":%{\" .. arg .. \"}}\");\n                if (name == nil or name == '') then\n                        break\n                end\n                args[arg] = name\n                arg = arg + 1\n        end\n        for arg, name in ipairs(args) do\n                canonical = rpm.expand(\"%py_dist_name \" .. name);\n                print(\"python3dist(\" .. canonical .. \") \");\n        end\n}",
    "py3_install": "%{expand:\\\n  CFLAGS=\"${CFLAGS:-${RPM_OPT_FLAGS}}\" LDFLAGS=\"${LDFLAGS:-${RPM_LD_FLAGS}}\"\\\n  %{__python3} %{py_setup} %{?py_setup_args} install -O1 --skip-build --root %{buildroot} %{?*}\n}",
    "py3_install_egg": "%{expand:\\\n  mkdir -p %{buildroot}%{python3_sitelib}\n  easy_install-%{python3_version} -m --prefix %{buildroot}%{_prefix} -Z dist/*-py%{python3_version}.egg %{?*}\n}",
    "py3_install_wheel": "%{expand:\\\n  pip%{python3_version} install -I dist/%{1} --root %{buildroot}  --no-deps\n}",
    "py3_other_build": "/bin/true",
    "py3_other_install": "/bin/true",
    "py3_shbang_opts": "-s",
    "py3dir": "%{_builddir}/python3-%{name}-%{version}-%{release}",
    "py_auto_byte_compile": "1",
    "py_build": "%{expand:\\\n  CFLAGS=\"${CFLAGS:-${RPM_OPT_FLAGS}}\" LDFLAGS=\"${LDFLAGS:-${RPM_LD_FLAGS}}\"\\\n  %{__python} %{py_setup} %{?py_setup_args} build --executable=\"%{__python} %{py_shbang_opts}\" %{?*}\n  sleep 1\n}",
    "py_build_egg": "%{expand:\\\n  CFLAGS=\"${CFLAGS:-${RPM_OPT_FLAGS}}\" LDFLAGS=\"${LDFLAGS:-${RPM_LD_FLAGS}}\"\\\n  %{__python} %{py_setup} %{?py_setup_args} bdist_egg %{?*}\n  sleep 1\n}",
    "py_build_wheel": "%{expand:\\\n  CFLAGS=\"${CFLAGS:-${RPM_OPT_FLAGS}}\" LDFLAGS=\"${LDFLAGS:-${RPM_LD_FLAGS}}\"\\\n  %{__python} %{py_setup} %{?py_setup_args} bdist_wheel %{?*}\n  sleep 1\n}",
    "py_byte_compile": "python_binary=\"%1\"\nbytecode_compilation_path=\"%2\"\nfind $bytecode_compilation_path -type f -a -name \"*.py\" -print0 | xargs -0 $python_binary -O -m py_compile\nfind $bytecode_compilation_path -type f -a -name \"*.py\" -print0 | xargs -0 $python_binary -m py_compile",
    "py_dist_name": "%{lua:\n        name = rpm.expand(\"%{?1:%{1}}\");\n        canonical = string.gsub(string.lower(name), \"[^%w%.]+\", \"-\");\n        print(canonical);\n}",
    "py_install": "%{expand:\\\n  CFLAGS=\"${CFLAGS:-${RPM_OPT_FLAGS}}\" LDFLAGS=\"${LDFLAGS:-${RPM_LD_FLAGS}}\"\\\n  %{__python} %{py_setup} %{?py_setup_args} install -O1 --skip-build --root %{buildroot} %{?*}\n}",
    "py_install_egg": "%{expand:\\\n  mkdir -p %{buildroot}%{python_sitelib}\n  easy_install -m --prefix %{buildroot}%{_prefix} -Z dist/*-py%{python_version}.egg %{?*}\n}",
    "py_install_wheel": "%{expand:\\\n  pip install -I dist/%{1} --root %{buildroot} --strip-file-prefix %{buildroot} --no-deps\n}",
    "py_setup": "setup.py",
    "py_shbang_opts": "-s",
    "pypi_source": "%{lua:\n    local src = rpm.expand('%1')\n    local ver = rpm.expand('%2')\n    local ext = rpm.expand('%3')\n    local url = rpm.expand('%__pypi_url')\n\n    -- If no first argument, try %srcname, then %pypi_name, then %name\n    -- Note that rpm leaves macros unchanged if they are not defined.\n    if src == '%1' then\n        src = rpm.expand('%srcname')\n    end\n    if src == '%srcname' then\n        src = rpm.expand('%pypi_name')\n    end\n    if src == '%pypi_name' then\n        src = rpm.expand('%name')\n    end\n\n    -- If no second argument, use %version\n    if ver == '%2' then\n        ver = rpm.expand('%version')\n    end\n\n    -- If no third argument, use the preset default extension\n    if ext == '%3' then\n        ext = rpm.expand('%__pypi_default_extension')\n    end\n\n    local first = string.sub(src, 1, 1)\n\n    print(url .. first .. '/' .. src .. '/' .. src .. '-' .. ver .. '.' .. ext)\n}",
    "python2_sitearch": "%(%{__python2} -Esc \"from distutils.sysconfig import get_python_lib; print(get_python_lib(1))\")",
    "python2_sitelib": "%(%{__python2} -Esc \"from distutils.sysconfig import get_python_lib; print(get_python_lib())\")",
    "python2_version": "%(%{__python2} -Esc \"import sys; sys.stdout.write('{0.major}.{0.minor}'.format(sys.version_info))\")",
    "python2_version_nodots": "%(%{__python2} -Esc \"import sys; sys.stdout.write('{0.major}{0.minor}'.format(sys.version_info))\")",
    "python3_pkgversion": "3",
    "python3_platform": "%(%{__python3} -Ic \"import sysconfig; print(sysconfig.get_platform())\")",
    "python3_sitearch": "%(%{__python3} -Ic \"from distutils.sysconfig import get_python_lib; print(get_python_lib(1))\")",
    "python3_sitelib": "%(%{__python3} -Ic \"from distutils.sysconfig import get_python_lib; print(get_python_lib())\")",
    "python3_version": "%(%{__python3} -Ic \"import sys; sys.stdout.write('{0.major}.{0.minor}'.format(sys.version_info))\")",
    "python3_version_nodots": "%(%{__python3} -Ic \"import sys; sys.stdout.write('{0.major}{0.minor}'.format(sys.version_info))\")",
    "python_enable_dependency_generator": "%global __pythondist_requires %{_rpmconfigdir}/pythondistdeps.py --requires \n%{nil}",
    "python_provide": "%{lua:\n  function string.starts(String,Start)\n    return string.sub(String,1,string.len(Start))==Start\n  end\n  package = rpm.expand(\"%{?1}\")\n  vr = rpm.expand(\"%{?epoch:%{epoch}:}%{version}-%{release}\")\n  if (string.starts(package, \"python2-\")) then\n    --No unversioned provides as python2 is not default\n  elseif (string.starts(package, \"python\" .. rpm.expand(\"%{python3_pkgversion}\") .. \"-\")) then\n    print(\"\\nProvides: python-\")\n    l = 8 + string.len(rpm.expand(\"%{python3_pkgversion}\"))\n    print(string.sub(package,l,string.len(package)))\n    print(\" = \")\n    print(vr)\n    --Obsoleting the previous default python package (if it doesn't have isa)\n    if (string.sub(package, \"-1\") ~= \")\") then\n      print(\"\\nObsoletes: python-\")\n      print(string.sub(package,l,string.len(package)))\n      print(\" < \")\n      print(vr)\n    end\n  elseif (rpm.expand(\"%{?python3_other_pkgversion}\") ~= \"\" and string.starts(package, \"python\" .. rpm.expand(\"%{python3_other_pkgversion}\") .. \"-\")) then\n    --No unversioned provides as python3_other is not default\n  elseif (string.starts(package, \"pypy-\")) then\n    --No unversioned provides as pypy is not default\n  elseif (string.starts(package, \"pypy2-\")) then\n    --No unversioned provides as pypy is not default\n  elseif (string.starts(package, \"pypy3-\")) then\n    --No unversioned provides as pypy is not default\n  elseif (string.starts(package, \"python-\")) then\n    --No unversioned provides needed for unversioned python\n  else\n    print(\"%python_provide: ERROR: \")\n    print(package)\n    print(\" not recognized.\")\n  end\n}",
    "python_sitearch": "%(%{__python} -c \"from distutils.sysconfig import get_python_lib; import sys; sys.stdout.write(get_python_lib(1))\")",
    "python_sitelib": "%(%{__python} -c \"from distutils.sysconfig import get_python_lib; import sys; sys.stdout.write(get_python_lib())\")",
    "python_version": "%(%{__python} -c \"import sys; sys.stdout.write(sys.version[:3])\")",
    "qt5_qtwebengine_arches": "%{ix86} x86_64 %{arm} aarch64 mips mipsel mips64el",
    "requires_eq": "%(LC_ALL=\"C\" echo '%*' | xargs -r rpm -q --qf 'Requires: %%{name} = %%{epoch}:%%{version}\\n' | sed -e 's/ (none):/ /' -e 's/ 0:/ /' | grep -v \"is not\")",
    "riscv": "%{riscv32} %{riscv64} %{riscv128}",
    "riscv128": "riscv128",
    "riscv32": "riscv32",
    "riscv64": "riscv64",
    "rpm_vercmp": "%{lua:print(rpm.expand('%1') == '~~~' and '~~~' or rpm.vercmp(rpm.expand('%1'), rpm.expand('%2')))}",
    "rpmmacrodir": "/usr/lib/rpm/macros.d",
    "set_build_flags": "CFLAGS=\"${CFLAGS:-%{build_cflags}}\" ; export CFLAGS ; \n  CXXFLAGS=\"${CXXFLAGS:-%{build_cxxflags}}\" ; export CXXFLAGS ; \n  FFLAGS=\"${FFLAGS:-%{build_fflags}}\" ; export FFLAGS ; \n  FCFLAGS=\"${FCFLAGS:-%{build_fflags}}\" ; export FCFLAGS ; \n  LDFLAGS=\"${LDFLAGS:-%{build_ldflags}}\" ; export LDFLAGS",
    "source_date_epoch_from_changelog": "0",
    "sources": "%{lua: for i, s in ipairs(sources) do print(s..\" \") end}",
    "sparc": "sparc sparcv8 sparcv9 sparcv9v sparc64 sparc64v",
    "sysctl_apply": "%{expand:%%{?__systemd_someargs_%#:%%__systemd_someargs_%# sysctl_apply}} \n[ -x /usr/lib/systemd/systemd-sysctl ] && /usr/lib/systemd/systemd-sysctl %{?*} || : \n%{nil}",
    "systemd_ordering": "OrderWithRequires(post): systemd \nOrderWithRequires(preun): systemd \nOrderWithRequires(postun): systemd \n%{nil}",
    "systemd_post": "%{expand:%%{?__systemd_someargs_%#:%%__systemd_someargs_%# systemd_post}} \nif [ $1 -eq 1 ] && [ -x %{_bindir}/systemctl ]; then \n    # Initial installation \n    %{_bindir}/systemctl --no-reload preset %{?*} || : \nfi \n%{nil}",
    "systemd_postun": "%{expand:%%{?__systemd_someargs_%#:%%__systemd_someargs_%# systemd_postun}} \n%{nil}",
    "systemd_postun_with_restart": "%{expand:%%{?__systemd_someargs_%#:%%__systemd_someargs_%# systemd_postun_with_restart}} \nif [ $1 -ge 1 ] && [ -x %{_bindir}/systemctl ]; then \n    # Package upgrade, not uninstall \n    for unit in %{?*}; do \n         %{_bindir}/systemctl set-property $unit Markers=+needs-restart || : \n    done \nfi \n%{nil}",
    "systemd_preun": "%{expand:%%{?__systemd_someargs_%#:%%__systemd_someargs_%# systemd_preun}} \nif [ $1 -eq 0 ] && [ -x %{_bindir}/systemctl ]; then \n    # Package removal, not upgrade \n    if [ -d /run/systemd/system ]; then \n          %{_bindir}/systemctl --no-reload disable --now %{?*} || : \n    else \n          %{_bindir}/systemctl --no-reload disable %{?*} || : \n    fi \nfi \n%{nil}",
    "systemd_requires": "Requires(post): systemd \nRequires(preun): systemd \nRequires(postun): systemd \n%{nil}",
    "systemd_user_post": "%{expand:%systemd_post \\--global %%{?*}}",
    "systemd_user_postun": "%{expand:%%{?__systemd_someargs_%#:%%__systemd_someargs_%# systemd_user_postun}} \n%{nil}",
    "systemd_user_postun_with_restart": "%{expand:%%{?__systemd_someargs_%#:%%__systemd_someargs_%# systemd_postun_with_restart}} \n%{nil}",
    "systemd_user_preun": "%{expand:%%{?__systemd_someargs_%#:%%__systemd_someargs_%# systemd_user_preun}} \nif [ $1 -eq 0 ] && [ -x %{_bindir}/systemctl ]; then \n    # Package removal, not upgrade \n    %{_bindir}/systemctl --global disable %{?*} || : \nfi \n%{nil}",
    "sysusers_create": "%{expand:%%{?__systemd_someargs_%#:%%__systemd_someargs_%# sysusers_create}} \n[ -x %{_bindir}/systemd-sysusers ] && %{_bindir}/systemd-sysusers %{?*} || : \n%{nil}",
    "sysusers_create_inline": "[ -x %{_bindir}/systemd-sysusers ] && %{_bindir}/systemd-sysusers - <<SYSTEMD_INLINE_EOF || : \n%{?*} \nSYSTEMD_INLINE_EOF\n%{nil}",
    "sysusers_create_package": "%{expand:%%{?!__systemd_twoargs_%#:%%{error:The %%%%sysusers_create_package macro requires two arguments}}} \nsystemd-sysusers --replace=%_sysusersdir/%1.conf - <<SYSTEMD_INLINE_EOF || : \n%(cat %2) \nSYSTEMD_INLINE_EOF\n%{nil}",
    "tests_req": "%{expand:\nBuildRequires: %*\n%%tests_subpackage_requires %*\n}",
    "tests_subpackage_provides": "%{expand:\n%global __tests_spkg_prov %{?__tests_spkg_prov} %* \n}",
    "tests_subpackage_requires": "%{expand:\n%global __tests_spkg_req %{?__tests_spkg_req} %* \n}",
    "tmpfiles_create": "%{expand:%%{?__systemd_someargs_%#:%%__systemd_someargs_%# tmpfiles_create}} \n[ -x %{_bindir}/systemd-tmpfiles ] && %{_bindir}/systemd-tmpfiles --create %{?*} || : \n%{nil}",
    "tmpfiles_create_package": "%{expand:%%{?!__systemd_twoargs_%#:%%{error:The %%%%tmpfiles_create_package macro requires two arguments}}} \nsystemd-tmpfiles --replace=%_tmpfilesdir/%1.conf --create - <<SYSTEMD_INLINE_EOF || : \n%(cat %2) \nSYSTEMD_INLINE_EOF\n%{nil}",
    "udev_hwdb_update": "%{nil}",
    "udev_rules_update": "%{nil}",
    "undefined": "%{expand:%%{?%{1}:0}%%{!?%{1}:1}}",
    "use_source_date_epoch_as_buildtime": "0",
    "valgrind_arches": "%{generic_arches}",
    "with": "%{expand:%%{?with_%{1}:1}%%{!?with_%{1}:0}}",
    "without": "%{expand:%%{?with_%{1}:0}%%{!?with_%{1}:1}}\n======================== active 562 empty 0"
}
