SHELL_KEYWORDS = ["build", "install", "prep", "check", "clean", "pre", "preun", "pretrans", "post", "postun",
                  "posttrans", "configure"]
OBS_LINES_KEYWORDS = ["description", "files"]
MAIN_SHELL_KEYWORDS = ["build", "install", "prep", "check", "clean"]
MACROS_KEYWORDS = ["%package_help"]

HEADERS = ('package',
           'description',
           'prep',
           'build',
           'install',
           'clean',
           'check',
           'preun',
           'pretrans',
           'pre',
           'postun',
           'posttrans',
           'post',
           'files',
           'changelog',
           'include')
SINGLES = ('Summary',
           'Name',
           'Version',
           'Epoch',
           'URL',
           'Group',
           'BuildArch',
           'Source',
           'Patch',
           'Prefix',
           'License')
REQUIRES = ('BuildRequires',
            'Requires',
            'Requires(post)',
            'Requires(postun)',
            'Requires(posttrans)',
            'Requires(pre)',
            'PreRequires', 'PreReq', 'Prereq',  # alias in old spec
            'Requires(preun)',
            'Requires(pretrans)',
            'Provides',
            'Obsoletes',
            'Conflicts',
            'BuildConflicts',
            'FilesJudgement',
            )
SKIPS = ('BuildRoot',)

ORDER_ENTRIES = ['Macros',
                 'Name',
                 'Summary',
                 'Version',
                 'Release',
                 'Epoch',
                 'Group',
                 'License',
                 'URL',
                 'SCM',
                 'Sources',
                 'ExtraSources',
                 'Patches',
                 'Description',
                 'Requires',
                 'RequiresPre',
                 'RequiresPreUn',
                 'RequiresPreTrans',
                 'RequiresPost',
                 'RequiresPostUn',
                 'RequiresPostTrans',
                 'BuildRequires',
                 'Provides',
                 'Obsoletes',
                 'Conflicts',
                 'ConfigOptions',
                 'BuildArch',
                 'ExclusiveArch',
                 'LocaleName',
                 'LocaleOptions',
                 'Files',
                 'FilesInput',
                 'SupportOtherDistros',
                 'ExclusiveArch',
                 'ExcludeArch',
                 'Recommends',
                 'Supplements',
                 'Prefix',
                 'OrderWithRequires',
                 'Suggests',
                 'IncludeSource',
                 'FilesJudgement',
                 'rpmMacros'
                 ]
# must have keys for 'main' package
MUSTHAVE = {'Release': '1',
            }

TAB = '    '  # 4space, instead of Tab
KEY_SYS = {
            'BuildRequires': 'BuildRequires',
            'description': 'Description',
            'Requires(post)': 'RequiresPost',
            'Requires(postun)': 'RequiresPostUn',
            'Requires(posttrans)': 'RequiresPostTrans',
            'Requires(pre)': 'RequiresPre',
            'PreRequires': 'RequiresPre',
            'PreReq': 'RequiresPre',
            'Prereq': 'RequiresPre',
            'Requires(preun)': 'RequiresPreUn',
            'Requires(pretrans)': 'RequiresPreTrans',
            'Url': 'URL',
            'install': 'Install',
            'build': 'Build',
            'files': 'Files',
            'clean': 'Clean',
            'pre': 'Pre',
            'preun': 'Preun',
            'post': 'Post',
            'postun': 'Postun',
            'pretrans': 'Pretrans',
            'posttrans': 'Posttrans',
            'check': 'Check',
            'prep': 'Prep',
            'include': 'IncludeSource',
            'Autoreq': 'AutoReq',
            'Autoprov': 'AutoProv',
            'Autoreqprov': 'AutoReqProv',
        }

SPEC_EXTRA_KEYS = {
        # key -> ( nkey, nsubkey)
        #                ^^ None means to use <pkg_name>
        'Files': ('files', None),
        'macros': ('macros', None),
        'setup': ('setup', None),
        'define': ('define', None),
        'undefine': ('undefine', None),
        'global': ('global', None),
        'PostMakeInstallExtras': ('install', 'post'),
        'PreMakeInstallExtras': ('install', 'pre'),
        'PostMakeExtras': ('build', 'post'),
        'PreMakeExtras': ('build', 'pre'),
    }
